# Generated by Django 3.0.6 on 2020-07-23 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(default=datetime.date.today)),
                ('enddate', models.DateField(default=datetime.date.today)),
                ('swipes', models.IntegerField(default=0)),
                ('lenoir', models.BooleanField(default=True)),
                ('chase', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('brunch', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('dinner', models.BooleanField(default=True)),
                ('judgeoptions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needsjudgement', models.BooleanField(default=True)),
                ('option', models.TextField(unique=True)),
                ('score', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('meal', models.TextField(choices=[('breakfast', 'breakfast'), ('brunch', 'brunch'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('none', 'none')])),
                ('location', models.TextField(choices=[('lenoir', 'lenoir'), ('chase', 'chase')])),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.Input_Data')),
                ('options', models.ManyToManyField(to='input_data.Option')),
            ],
            options={
                'ordering': ['date', 'meal'],
            },
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('date', 'meal', 'location'), name='unique_meal_at_location'),
        ),
    ]
