# Generated by Django 3.0.6 on 2020-08-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='name',
            new_name='optionname',
        ),
    ]
