# Generated by Django 3.0.6 on 2020-06-01 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0002_auto_20200601_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_data',
            name='dates',
        ),
        migrations.AddField(
            model_name='input_data',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input_data',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
