# Generated by Django 3.0.6 on 2020-08-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0002_auto_20200803_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_data',
            name='swipes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
