# Generated by Django 3.0.6 on 2020-07-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0002_input_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_data',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='brunch',
            field=models.BooleanField(default=False),
        ),
    ]
