# Generated by Django 3.0.6 on 2020-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0004_meal_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
