# Generated by Django 3.0.6 on 2020-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0006_auto_20200602_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_data',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='brunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='chase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='lenoir',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='lunch',
            field=models.BooleanField(default=True),
        ),
    ]
