# Generated by Django 3.0.6 on 2020-06-04 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0007_auto_20200602_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='location',
            field=models.TextField(choices=[('lenoir', 'lenoir'), ('chase', 'chase')], default='lenoir'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input_data',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='input_data',
            name='swipes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.TextField(choices=[('breakfast', 'breakfast'), ('brunch', 'brunch'), ('lunch', 'lunch'), ('dinner', 'dinner')]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, 'SuperLike')], default=0),
        ),
    ]
