# Generated by Django 3.0.6 on 2020-06-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0008_auto_20200604_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='score',
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('date', 'meal', 'location'), name='unique_meal_at_location'),
        ),
    ]
