# Generated by Django 3.0.6 on 2020-06-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0010_auto_20200617_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='needs_judgement',
            field=models.BooleanField(default=True),
        ),
    ]
