# Generated by Django 3.0.6 on 2020-06-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0011_option_needs_judgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.BooleanField(default=False),
        ),
    ]
