# Generated by Django 3.0.6 on 2020-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0014_auto_20200701_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['date', 'meal']},
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.TextField(choices=[('0', 'breakfast'), ('1', 'brunch'), ('2', 'lunch'), ('3', 'dinner'), ('none', 'none')]),
        ),
    ]
