# Generated by Django 3.0.6 on 2020-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0021_auto_20200706_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_data',
            name='judge_options',
            field=models.BooleanField(default=False),
        ),
    ]
